Repository theopenconversationkit/tock-react-kit, pull requests merged in 2021-10, with the labels that each got.

#72 resolve #71: Make Quick Reply buttons wrap over
  src/components/QuickReplyList/QuickReplyList.tsx
Labels: enhancement

#76 Bump deps + circular imports
  .storybook/addons.js
  package.json
  src/components/Chat/Chat.stories.tsx
  src/components/Conversation/Conversation.stories.tsx
  src/renderChat.tsx
  src/styles/tockThemeProvider.ts
  yarn.lock
Labels: dependencies

#78 resolve #32 disable SSE option
  README.md
  src/Sse.ts
  src/TockOptions.ts
  src/components/Chat/Chat.tsx
  src/renderChat.tsx
  src/useTock.ts
Labels: enhancement

#77 fix #69 #73 opening message + extra headers
  README.md
  src/components/Chat/Chat.tsx
  src/useTock.ts
Labels: bug
